### ISSUE TITLE
Change replyTo in schema.sql

### ISSUE THREAD

**Issue by ShittyDev-trustme** [cyberland-digital/cyberland#5]
Wouldn't it be better if you changed the replyTo fields in your schema.sql from

replyTo integer default null,

to

replyTo integer default 0 not null,

This would make the saved data more consistent and usuable for the frontends imo
Replying to 0 and repyling to null is the practically the same for creating a new thread but new frontends wouldn't have to adjust to those both cases.

(added rfc cause i can't add any labels)

**Comment by JamesVStone** [comment]
That would make more sence
