### ISSUE TITLE
Create GitHub Image

### ISSUE THREAD

**Issue by JamesVStone** [cyberland-digital/cyberland#6]
A stylized JPEG of the ascii logo would be cool. But if you dare to dream, why not bigger?

**Comment by JamesVStone** [comment]
640×320px (1280×640px for best display).

**Comment by ojoeth** [comment]
![cyberland](https://user-images.githubusercontent.com/59626080/79393499-5efca580-7f6d-11ea-9d2f-496e4a809d5e.png)

**Comment by ojoeth** [comment]
closed wontfix
